version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
      - ./api:/var/www/api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    container_name: mysql-h
    restart: unless-stopped
    tty: true
    ports:
      - "3306-3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rh
      MYSQL_USER: root
      MYSQL_PASSWORD: remzihoca
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - mysql
      - pgsql
    volumes:
      - ./web:/var/www/html
    ports:
      - "9000-9000"
    networks:
      - laravel
  node:
    build:
      context: api/
      dockerfile: node.dockerfile
    container_name: nodeApi
    volumes:
      - ./api:/home/app
    ports:
      - "3000:3000"
    networks:
      - laravel
  pgsql:
    image: postgres
    restart: always
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - laravel

